# Generated by Django 4.1.7 on 2024-03-29 13:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('chatbot', '0002_rename_user_chat_userr'),
    ]

    operations = [
        migrations.RenameField(
            model_name='chat',
            old_name='userr',
            new_name='user',
        ),
    ]
