# Generated by Django 4.1.7 on 2024-03-28 15:41

import cloudinary.models
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0012_course_discount_course_price'),
    ]

    operations = [
        migrations.CreateModel(
            name='Lesson',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('lesson_number', models.IntegerField(default=1, unique=True)),
                ('lesson_title', models.CharField(default='Lesson', max_length=255)),
                ('lesson_video', cloudinary.models.CloudinaryField(max_length=255, null=True, verbose_name='lesson_video')),
                ('paragraph1', models.TextField()),
                ('paragraph2', models.TextField()),
                ('paragraph3', models.TextField()),
                ('course', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lessons', to='main.course')),
            ],
        ),
    ]
