# Generated by Django 4.1.7 on 2024-03-28 15:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0013_lesson'),
    ]

    operations = [
        migrations.RenameField(
            model_name='lesson',
            old_name='lesson_number',
            new_name='lesson_no',
        ),
    ]
