# Generated by Django 4.1.7 on 2024-03-29 10:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0015_alter_lesson_lesson_no_alter_lesson_lesson_video'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lesson',
            name='lesson_no',
            field=models.TextField(default=1),
        ),
    ]
